-- Create 'bookings' table
create table public.bookings (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  seats text not null, -- Store as comma separated string for simplicity in display
  total_price integer not null,
  event_id bigint references public.events(id),
  created_at timestamp with time zone default now()
);

-- Enable RLS
alter table public.bookings enable row level security;

-- Policies
create policy "Admins can view bookings" 
on public.bookings for select using (auth.role() = 'authenticated');

create policy "Admins can insert bookings" 
on public.bookings for insert with check (auth.role() = 'authenticated' or true); -- Allow public to book

create policy "Admins can update bookings" 
on public.bookings for update using (auth.role() = 'authenticated');

create policy "Admins can delete bookings" 
on public.bookings for delete using (auth.role() = 'authenticated');
