-- Enable Row Level Security
alter default privileges revoke execute on functions from public;

-- 1. Create 'events' table
create table public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  date text,
  location text,
  description text,
  image text,
  category text,
  duration text,
  director text,
  cast_members jsonb -- Store array of strings as JSON
);

-- 2. Create 'seats' table
create table public.seats (
  id text primary key, -- Use 'row-seat' (e.g., '1-5') as ID
  row_num integer not null, -- Renamed from 'row' to avoid keyword conflict
  seat_num integer not null, -- Renamed from 'seat'
  type text check (type in ('vip', 'standard', 'budget')),
  price integer default 500,
  is_booked boolean default false,
  event_id bigint references public.events(id)
);

-- 3. Enable RLS (Row Level Security)
alter table public.events enable row level security;
alter table public.seats enable row level security;

-- 4. Create Policies
-- Allow everyone to READ events and seats
create policy "Public events are viewable by everyone" 
on public.events for select using (true);

create policy "Public seats are viewable by everyone" 
on public.seats for select using (true);

-- Allow authenticated (admin) users to UPDATE/INSERT/DELETE
create policy "Admins can update events" 
on public.events for all using (auth.role() = 'authenticated');

create policy "Admins can update seats" 
on public.seats for all using (auth.role() = 'authenticated');

-- 5. Insert Initial Data (The "Esfir" Event)
insert into public.events (title, date, location, description, image, category, duration, director, cast_members)
values (
  'Esfir',
  'Mars 15, 2024 • 19:00',
  'National Drama Theatre',
  'A powerful and emotionally charged dramatic retelling of the biblical story of Esther (Esfir). Witness the journey of a young Jewish woman who becomes Queen of Persia and risks her life to save her people from destruction.',
  '/esfir_poster.png',
  'Drama',
  '2h 30m (with intermission)',
  'A. K. Directorov',
  '["Sarah Cohen as Esfir", "David King as Mordecai", "Xerxes the Great as King Ahasuerus"]'
);
